// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYVUwJXWvG1bEQASScRIn97k0ju8cUVz4',
    appId: '1:318769371927:android:4a57c5ac2160c903b9b552',
    messagingSenderId: '318769371927',
    projectId: 'plutonic-0000',
    storageBucket: 'plutonic-0000.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8gtO6iNjK04WdMb045HIFmcyhBOQt38',
    appId: '1:318769371927:web:df5802126920fd43b9b552',
    messagingSenderId: '318769371927',
    projectId: 'plutonic-0000',
    authDomain: 'plutonic-0000.firebaseapp.com',
    storageBucket: 'plutonic-0000.appspot.com',
    measurementId: 'G-989Q3D485K',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzsm8EMlfpIrxjHYgFb5mseaw8c0cYl78',
    appId: '1:318769371927:ios:6999dc432f7f92b7b9b552',
    messagingSenderId: '318769371927',
    projectId: 'plutonic-0000',
    storageBucket: 'plutonic-0000.appspot.com',
    iosBundleId: 'com.example.plutonic',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzsm8EMlfpIrxjHYgFb5mseaw8c0cYl78',
    appId: '1:318769371927:ios:6999dc432f7f92b7b9b552',
    messagingSenderId: '318769371927',
    projectId: 'plutonic-0000',
    storageBucket: 'plutonic-0000.appspot.com',
    iosBundleId: 'com.example.plutonic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8gtO6iNjK04WdMb045HIFmcyhBOQt38',
    appId: '1:318769371927:web:f4ecd1cd479f79b3b9b552',
    messagingSenderId: '318769371927',
    projectId: 'plutonic-0000',
    authDomain: 'plutonic-0000.firebaseapp.com',
    storageBucket: 'plutonic-0000.appspot.com',
    measurementId: 'G-641N2SCSZK',
  );

}